# Generated by Django 4.2.6 on 2023-11-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=7, unique=True)),
                ("admin_name", models.CharField(max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AttendanceLog",
            fields=[
                ("serial_number", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.CharField(max_length=255)),
                ("course_name", models.CharField(max_length=255)),
                ("semester", models.CharField(max_length=50)),
                ("professor_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="LoginCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=7, unique=True)),
                ("teacher_name", models.CharField(max_length=40)),
                ("email", models.CharField(max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
